import { NextPage } from "next";
import React, { ReactNode } from "react";
import Head from "next/head";
import Link from "next/link";
type AppLayoutProps = {
  children: ReactNode;
};

const AppLayout: React.FC<AppLayoutProps> = ({ children }) => {
  return (
    <>
      <Head>
        <meta name="description" content="Generated by Create Next Stack." />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link
          href="https://cdn.jsdelivr.net/npm/daisyui@4.6.1/dist/full.min.css"
          rel="stylesheet"
          type="text/css"
        />
      </Head>
      <div className="min-h-screen">
        <div className="navbar bg-base-100">
          <div className="flex-1">
            <a className="btn btn-ghost text-xl">Books</a>
          </div>
          <div className="flex-none">
            <ul className="menu menu-horizontal px-1">
              <Link href="/categories">
                <button className="btn btn-sm  btn-success mr-2">
                  Categories
                </button>
              </Link>
              <Link href="/books">
                <button className="btn btn-sm btn-info mr-2">Books</button>
              </Link>
            </ul>
          </div>
        </div>
        {children}
      </div>
    </>
  );
};

export default AppLayout;
